# Generated by Django 4.2.16 on 2024-10-31 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("home_latitude", models.FloatField(null=True)),
                ("home_longitude", models.FloatField(null=True)),
                ("work_latitude", models.FloatField(null=True)),
                ("work_longitude", models.FloatField(null=True)),
                ("fav_source_latitude", models.FloatField(null=True)),
                ("fav_source_longitude", models.FloatField(null=True)),
                ("fav_dest_latitude", models.FloatField(null=True)),
                ("fav_dest_longitude", models.FloatField(null=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "fav_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.station",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
