# Generated by Django 5.1.1 on 2024-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
