# Generated by Django 5.1.1 on 2024-11-07 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
