# Generated by Django 5.1.1 on 2024-11-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_review_create_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
