# Generated by Django 5.1.1 on 2024-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
